# --- Configuración Global ---
# Se define una sola vez para todo el broker
allow_anonymous false
password_file /mosquitto/secrets/passwordfile
acl_file /mosquitto/config/acl

# Persistencia (Opcional pero recomendada)
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_dest file /mosquitto/log/mosquitto.log

# --- Listeners ---

# MQTT Estándar
listener 1883 0.0.0.0
protocol mqtt

# WebSockets (Para dashboards web)
listener 9001 0.0.0.0
protocol websockets
